language: python
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
# command to run tests
script:
  - python manage.py test
services:
  - postgresql
before_script:
  - psql -c "CREATE USER vft;" -U vft
  - psql -c 'create database purbeurre;' -U vft
